src/Pyz/Yves/CatalogPage/Controller/CatalogController.php
src/Pyz/Yves/CatalogPage/Theme/default/templates/page-layout-catalog/page-layout-catalog.twig

- Ticket: https://spryker.atlassian.net/browse/SUITE-212

SUITE-212: Add banner path to category data set

---

src/Pyz/Yves/CatalogPage/Controller/CatalogController.php

- Ticket: https://spryker.atlassian.net/browse/SUITE-212

SUITE-212: Add category id to banner path

---

src/Pyz/Yves/CustomerReorderWidget/CustomerReorderWidgetFactory.php
src/Pyz/Yves/CustomerReorderWidget/Model/CartFiller.php

- Ticket: https://spryker.atlassian.net/projects/SUITE/issues/SUITE-72

SUITE-72: Fix re-order feature

---

src/Pyz/Yves/ShopUi/Theme/default/components/organisms/navigation-top/navigation-top.twig

- Ticket: https://spryker.atlassian.net/projects/SUITE/issues/SUITE-71

SUITE-71: remove net/gross price mode switcher

---

data/import/icecat_biz_data/product_image.csv

SUITE-261: Update content

---

src/Pyz/Yves/CatalogPage/Theme/default/templates/page-layout-catalog/page-layout-catalog.twig

* Moved cmsTop block to content scope
- Ticket: https://spryker.atlassian.net/projects/SUITE/issues/SUITE-295

SUITE-295: Duplicate category content

---

src/Pyz/Yves/ProductReviewWidget/Theme/default/views/product-abstract-review-display/product-abstract-review-display.twig

* Hide product rating if empty
- Ticket: https://spryker.atlassian.net/projects/SUITE/issues/SUITE-296

SUITE-256: Improve product view

---

src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig

* Add active class to selected category
* Remove numbers of items
- Ticket: https://spryker.atlassian.net/projects/SUITE/issues/SUITE-308

SUITE-308: category tree logic

---

data/import/category.csv

- Ticket: https://spryker.atlassian.net/projects/SUITE/issues/SUITE-306

SUITE-306: remove unnecessary categories

---

src/Pyz/Yves/CatalogPage/Controller/CatalogController.php

- Ticket: https://spryker.atlassian.net/projects/SUITE/issues/SUITE-307

SUITE-307: Update Category title background logic

---

src/Pyz/Yves/ProductReviewWidget/Theme/default/components/molecules/rating-selector/rating-selector.twig
src/Pyz/Yves/ProductReviewWidget/Theme/default/views/pdp-review/pdp-review.twig
src/Pyz/Yves/ProductReviewWidget/Theme/default/views/product-abstract-review-display/product-abstract-review-display.twig
src/Pyz/Yves/ProductWidget/Theme/default/views/catalog-product/catalog-product.twig

- Ticket: https://spryker.atlassian.net/projects/SUITE/issues/SUITE-311

SUITE-319: Display reviews count next to the rating

---

data/import/cms_block.csv
frontend/assets/images/right-chevron.svg
src/Pyz/Shared/CmsBlock/Theme/default/template/product_slider_block.twig
src/Pyz/Yves/HomePage/Theme/default/templates/page-layout-home/page-layout-home.twig
src/Pyz/Yves/ProductRelationWidget/Theme/default/templates/similar-products/similar-products.twig
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-header/navigation-header.scss
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-slider-title/product-slider-title.scss
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/slick-carousel/slick-carousel.scss
src/Pyz/Yves/ShopUi/Theme/default/components/organisms/jumbotron-slider/jumbotron-slider.twig

products slider cart page

---

data/import/cms_block.csv

Home page content updated

---

data/import/cms_block.csv
data/import/cms_block_store.csv

Csv for home page blocks fix

---

data/import/glossary.csv
src/Pyz/Yves/CartNoteWidget/Theme/default/views/cart-note-form/cart-note-form.twig
src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-item-quantity-input/cart-item-quantity-input.scss
src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-item-quantity-input/cart-item-quantity-input.twig
src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-item-summary/cart-item-summary.scss
src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-item-summary/cart-item-summary.twig
src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-item-variant-selector/cart-item-variant-selector.scss
src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-item-variant-selector/cart-item-variant-selector.twig
src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-item/cart-item.scss
src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-item/cart-item.twig
src/Pyz/Yves/CartPage/Theme/default/components/organisms/shopping-cart/shopping-cart.scss
src/Pyz/Yves/CartPage/Theme/default/views/cart/cart.twig
src/Pyz/Yves/DiscountWidget/Theme/default/views/cart-discount-voucher-form/cart-discount-voucher-form.twig
src/Pyz/Yves/ShopUi/Theme/default/components/atoms/button/button.scss

cart item options

---

data/import/cms_block.csv

Csv home small fix

---

src/Pyz/Yves/ProductReviewWidget/Form/ProductReviewForm.php
src/Pyz/Yves/ProductReviewWidget/ProductReviewWidgetFactory.php

- Ticket: https://spryker.atlassian.net/projects/SUITE/issues/SUITE-378

SUITE-378: Show correct order of fields for "Write a Review" form

---

src/Pyz/Client/ProductReview/ProductReviewConfig.php

- Ticket: https://spryker.atlassian.net/projects/SUITE/issues/SUITE-353

SUITE-353: Show 10 review per page

---

data/import/glossary.csv
src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-item-quantity-input/cart-item-quantity-input.scss
src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-item-quantity-input/cart-item-quantity-input.twig
src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-item/cart-item.twig
src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-toggler/cart-toggler.scss
src/Pyz/Yves/CartPage/Theme/default/components/molecules/promotion-item/promotion-item.scss
src/Pyz/Yves/DiscountPromotionWidget/Theme/default/views/cart-discount-promotion-products-list/cart-discount-promotion-products-list.twig
src/Pyz/Yves/ShopUi/Theme/default/components/atoms/button/button.scss

Cart page updates

---

src/Pyz/Shared/ProductUrlCartConnector/Transfer/product_url_cart_connector.transfer.xml
src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-item/cart-item.twig
src/Pyz/Zed/Cart/CartDependencyProvider.php
src/Pyz/Zed/ProductUrlCartConnector/Business/Expander/ProductUrlExpander.php
src/Pyz/Zed/ProductUrlCartConnector/Business/Expander/ProductUrlExpanderInterface.php
src/Pyz/Zed/ProductUrlCartConnector/Business/ProductUrlCartConnectorBusinessFactory.php
src/Pyz/Zed/ProductUrlCartConnector/Business/ProductUrlCartConnectorFacade.php
src/Pyz/Zed/ProductUrlCartConnector/Business/ProductUrlCartConnectorFacadeInterface.php
src/Pyz/Zed/ProductUrlCartConnector/Communication/Plugin/ProductUrlCartPlugin.php
src/Pyz/Zed/ProductUrlCartConnector/Communication/ProductUrlCartConnectorCommunicationFactory.php
src/Pyz/Zed/ProductUrlCartConnector/ProductUrlCartConnectorConfig.php
src/Pyz/Zed/ProductUrlCartConnector/ProductUrlCartConnectorDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/SUITE-377

SUITE-377: Pass url data to cart items

---

.travis.yml

TE-3552: Travis needs to be pinned down to a known working version.

---

.dockerignore
composer.json
config/Shared/config_default-docker.php
config/Shared/config_default.php
config/install/docker.yml
config/install/testing.yml
src/Pyz/Yves/ShopUi/Theme/default/styles/basics/_typography.scss

202001.0-p1 B2C release
- Fixed ACL configuration for the HealthCheck services, so that ZED endpoint is now accessible for a not logged-in user.

202001.0-p1 release

---

data/import/production/full_US.yml

- Ticket: https://spryker.atlassian.net/browse/CC-12538

CC-12583: Fixed wrong alignment in the data import file.

---

composer.json
composer.lock
src/Pyz/Glue/GlueApplication/GlueApplicationDependencyProvider.php
src/Pyz/Zed/DocumentationGeneratorRestApi/DocumentationGeneratorRestApiConfig.php

Ticket: https://spryker.atlassian.net/browse/CC-16706

CC-16706: Added support for nested relationships in swagger documentation.

---

composer.lock
src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-detail/order-detail.twig
src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-table/order-table.twig

Bugfix integrations

---

composer.json
composer.lock

- Ticket: https://spryker.atlassian.net/browse/CC-16744

CC-16744: Fixed swagger documentation for voucher endpoints.

---

composer.json
composer.lock

Updated guzzle package version

---

.github/workflows/ci.yml
deploy.ci.acceptance.mariadb.yml
deploy.ci.acceptance.yml

https://spryker.atlassian.net/browse/CC-26078

CC-26078: Add robot test

---

composer.lock
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/menu/menu.scss
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/nav-overlay/nav-overlay.scss
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/nav-overlay/nav-overlay.ts
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/nav-overlay/nav-overlay.twig
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/page-load-state/index.ts
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/page-load-state/page-load-state.ts
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/page-load-state/page-load-state.twig
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/search-form/search-form.twig
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/suggest-search/suggest-search.scss
src/Pyz/Yves/ShopUi/Theme/default/components/organisms/header/header.scss
src/Pyz/Yves/ShopUi/Theme/default/styles/helpers/_effect.scss
src/Pyz/Yves/ShopUi/Theme/default/styles/shared.scss
src/Pyz/Yves/ShopUi/Theme/default/templates/page-layout-main/page-layout-main.twig

- Ticket: https://spryker.atlassian.net/browse/CC-25095
- Internal demo shop PR: https://github.com/spryker/b2c-demo-shop-internal/pull/1249

CC-25095 Fixed black screen on page loading.

---

composer.lock
src/Pyz/Zed/Publisher/PublisherDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/SUPESC-618

SUPESC-618 Added customer access publisher trigger plugin

---

composer.lock
src/Pyz/Client/ProductDiscontinuedStorage/ProductDiscontinuedStorageConfig.php

Bug Ticket: https://spryker.atlassian.net/browse/CC-24698
Integration Ticket: https://spryker.atlassian.net/browse/CC-26350

CC-24698: Fixed discontinued product attributes label.

---

composer.json
composer.lock
config/Shared/config_default.php
deploy.aop-b2c-testing.yml
deploy.aop-demoshop-b2c.yml
deploy.aws-env-template.yml
deploy.ci.acceptance.mariadb.yml
deploy.ci.acceptance.yml
deploy.ci.api.mariadb.yml
deploy.ci.api.yml
deploy.ci.functional.mariadb.yml
deploy.ci.functional.yml
deploy.dev.yml
deploy.yml

- Ticket: https://spryker.atlassian.net/browse/SUPESC-606
Reference all core PRs for auto-link back-references.
Core PRs
- https://github.com/spryker/spryker/pull/9959

SUPESC-606 Fixed filtering by stores in Availability Notifications.

---

composer.json
composer.lock

- Ticket: https://spryker.atlassian.net/browse/PBC-1355
- Composer packages updated
`composer require spryker/search-http:^0.3.0`
`composer update spryker/product`

PBC-1355: Integrate SearchHttp into B2С Demo Shop (v1.2)

---

src/Pyz/Service/FileSystem/FileSystemDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/CC-4006

CC-4006 Fixed exception when uploading files with File Manager.  

---

composer.lock

Fixed Github actions.

---

src/Pyz/Client/ExampleProductSalePage/ExampleProductSalePageDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/CC-28197

CC-26834 Fixed exception on Sales page.

---

src/Pyz/Glue/EventDispatcher/EventDispatcherDependencyProvider.php
src/Pyz/Glue/GlueBackendApiApplication/GlueBackendApiApplicationDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/CC-28281

CC-28281 Enabled runtime events for Backend API.

---

composer.json
composer.lock
src/Pyz/Client/ProductCategoryStorage/ProductCategoryStorageDependencyProvider.php
src/Pyz/Yves/ProductDetailPage/Theme/default/views/pdp/pdp.twig

- Ticket: https://spryker.atlassian.net/browse/CC-26817
- Core PRs: 
- https://github.com/spryker/suite-nonsplit/pull/1846
- https://github.com/spryker/spryker/pull/7594
- https://github.com/spryker/spryker-shop/pull/791

CC-26817 Fixed breadcrumbs for a product integration.

---

src/Pyz/Yves/ShopUi/Theme/default/components/organisms/header/header.twig
src/Pyz/Yves/ShopUi/Theme/default/components/organisms/navigation-top/navigation-top.twig
src/Pyz/Yves/ShopUi/Theme/default/components/organisms/side-drawer/side-drawer.twig
src/Pyz/Yves/StoreWidget/Theme/default/views/switcher/switcher.twig

Ticket: https://spryker.atlassian.net/browse/CC-29246

CC-29246 Styling store switcher

---

composer.lock
src/Pyz/Zed/OauthClient/OauthClientConfig.php

- Ticket: https://spryker.atlassian.net/browse/PBC-1885 | https://spryker.atlassian.net/browse/PBC-1575
- Updated `spryker/oauth-client` to version `1.3.0` and added necessary config.

PBC-1575: Updated oauth-client after fix

---

composer.json
composer.lock
src/Pyz/Zed/CartCode/CartCodeDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/CC-29848

CC-21301: Fixed invalid checkout payment

---

composer.json
composer.lock
src/Pyz/Yves/EventDispatcher/EventDispatcherDependencyProvider.php
src/Pyz/Yves/WebProfilerWidget/WebProfilerWidgetDependencyProvider.php
src/Pyz/Zed/EventDispatcher/EventDispatcherDependencyProvider.php
src/Pyz/Zed/WebProfiler/WebProfilerDependencyProvider.php

https://spryker.atlassian.net/browse/SDK-2600

SDK-2600 Added profiler module.

---

composer.json
composer.lock
src/Pyz/Zed/OauthClient/OauthClientDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/APPS-6512

APPS-6512: Auth0 token should be reset when credentials are updated

---

deploy.spryker-b2cintt.yml

- Ticket: https://spryker.atlassian.net/browse/CC-29960

CC-29960: Added missing mail sender.

---

composer.json
composer.lock

- Ticket: https://spryker.atlassian.net/browse/CC-29918

CC-29918 Fixed AddressForm's city field input type.

---

composer.json
composer.lock

- Ticket: https://spryker.atlassian.net/browse/CC-29931

CC-29931 Update Sales module

---

deploy.spryker-b2cintt.yml

- Ticket: https://spryker.atlassian.net/browse/CC-30090

CC-30090 Adjust CORS configuration for demo shops GLUE APIs

---

deploy.aop-demoshop-b2c.yml
deploy.aws-env-template.yml
deploy.ci.acceptance.dynamic-store.yml
deploy.ci.acceptance.mariadb.dynamic-store.yml
deploy.ci.acceptance.mariadb.prefer-lowest.dynamic-store.yml
deploy.ci.acceptance.mariadb.yml
deploy.ci.acceptance.yml
deploy.ci.api.dynamic-store.yml
deploy.ci.api.mariadb.dynamic-store.yml
deploy.ci.api.mariadb.yml
deploy.ci.api.yml
deploy.ci.functional.dynamic-store.yml
deploy.ci.functional.mariadb.dynamic-store.yml
deploy.ci.functional.mariadb.prefer-lowest.dynamic-store.yml
deploy.ci.functional.mariadb.yml
deploy.ci.functional.yml
deploy.dev.dynamic-store.yml
deploy.dev.yml
deploy.dynamic-store.yml
deploy.spryker-dynamicstore.yml
deploy.yml

- Ticket: https://spryker.atlassian.net/browse/SC-15419

SC-15419 Integrated the new version of Jenkins into the all public demoshops

---

src/Pyz/Zed/Quote/QuoteConfig.php

- Ticket: https://spryker.atlassian.net/browse/SUPESC-783

SUPESC-783 Added missing integration for storing expenses in Quote.

---

.github/workflows/ci.yml

- Activate NPM checker for critical and high level vulnerabilities in CI

Activate NPM checker

---

deploy.dev.yml
tests/PyzTest/Yves/Application/Presentation/Controller/HomepageCest.php
tests/PyzTest/Yves/Application/_support/ApplicationPresentationTester.php
tests/PyzTest/Yves/Application/codeception.yml
tests/PyzTest/Zed/NavigationGui/Presentation/NavigationCRUDCest.php
tests/PyzTest/Zed/NavigationGui/_support/NavigationGuiPresentationTester.php
tests/PyzTest/Zed/Product/Business/ProductAbstractManagerTest.php
tests/PyzTest/Zed/Product/Business/ProductConcreteManagerTest.php
tests/PyzTest/Zed/ProductRelation/Presentation/ProductRelationCreateRelationCest.php
tests/PyzTest/Zed/ProductRelation/_support/ProductRelationPresentationTester.php

- Ticket: https://spryker.atlassian.net/browse/SUPESC-780

SUPESC-780 Fixed failing automated tests on local environment.

---

deploy.aop-consultant-b2c.yml

- Ticket: https://spryker.atlassian.net/browse/APPS-9501

APPS-9516: acp integration

---

composer.json
composer.lock
src/Pyz/Glue/GlueBackendApiApplicationGlueJsonApiConventionConnector/GlueBackendApiApplicationGlueJsonApiConventionConnectorDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/CC-31636
- Core PR: none

CC-31636 Add missing image set relationship to concrete product.

---

.github/workflows/ci.yml

- Ticket: https://spryker.atlassian.net/browse/CC-31641

CC-31641 Fixed CI build for robot tests

---

deploy.aop-b2c-testing.yml
deploy.aop-demoshop-b2c.yml

- Ticket: https://spryker.atlassian.net/browse/APPS-10315

[APPS-10315] Changed mb2 gateways with domains.

---

composer.json
composer.lock
src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form-field-list/address-item-form-field-list.twig
src/Pyz/Yves/CheckoutPage/Theme/default/views/address/address.twig

- Ticket: https://spryker.atlassian.net/browse/CC-31784
- Core PR: https://github.com/spryker/spryker-shop/pull/2421

CC-31784 Fixed preselected address state for multiple addresses at checkout

---

deploy.aop-b2c-testing.yml
deploy.aop-consultant-b2c.yml
deploy.aop-demoshop-b2c.yml

- Ticket: https://spryker.atlassian.net/browse/APPS-10665

[APPS-10665] Provided enpoints for TF related build.

---

src/Pyz/Yves/ShopUi/Theme/default/components/molecules/custom-select/custom-select.scss

- Ticket: https://spryker.atlassian.net/browse/CC-31810

CC-31810 Fixed header dropdowns

---

deploy.aop-b2c-testing.yml
deploy.aop-consultant-b2c.yml
deploy.aop-demoshop-b2c.yml

- Ticket: https://spryker.atlassian.net/browse/ACP-412

ACP-412: ACP Consultant B2C DemoShop is using new MB 2.0

---

data/import/common/common/product_stock.csv

- Ticket: https://spryker.atlassian.net/browse/CC-32217

CC-32217 Fixed Bundle items stock import data.

---

composer.lock
src/Pyz/Yves/ProductDetailPage/Theme/default/components/molecules/product-carousel/product-carousel.twig
src/Pyz/Yves/ProductImageWidget/Theme/default/components/molecules/image-gallery/image-gallery.twig

Ticket: https://spryker.atlassian.net/browse/CC-32378

CC-18186 Fixed color selector on PDP.

---

composer.lock
data/import/common/common/glossary.csv

- Ticket: https://spryker.atlassian.net/browse/FRW-6331

FRW-6331 Data Exchange API Complex Endpoints for GET request.

---

composer.lock
src/Pyz/Yves/CustomerPage/CustomerPageDependencyProvider.php
src/Pyz/Yves/Security/SecurityDependencyProvider.php
src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
src/Pyz/Yves/Validator/ValidatorDependencyProvider.php
src/Pyz/Zed/Application/ApplicationDependencyProvider.php
src/Pyz/Zed/Security/SecurityDependencyProvider.php
src/Pyz/Zed/Validator/ValidatorDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/FRW-5940

FRW-5940 Updated spryker to support symfony security modules v6

---

composer.json
composer.lock

- Ticket: https://spryker.atlassian.net/browse/SDK-5711

SDK-5711: Updated `evaluator` dependency.

---

deploy.aop-consultant-b2c.yml

- Ticket: https://spryker.atlassian.net/browse/ACP-2121

ACP-2121: Stripe Release fix

---

deploy.aop-b2c-testing.yml
deploy.aop-demoshop-b2c.yml

- Ticket: https://spryker.atlassian.net/browse/ACP-2217

ACP-2217: Stripe missing domains

---

composer.lock

Overview
Ticket: https://spryker.atlassian.net/browse/FRW-7414

FRW-7414 Updated composer.lock

---

.github/workflows/ci.yml
composer.lock
deploy.ci.api.mariadb.dynamic-store.robot.yml

FRW - 7451 added new yml file and adjusted ci yml with new robot job for dynamic multistore
- Ticket: https://spryker.atlassian.net/browse/FRW-7451

FRW- 7451 created new Robot API job for Dynamic Multistore

---

composer.lock

- Ticket: [https://spryker.atlassian.net/browse/CC-33122]

CC-33122 Updated composer.loc file for robot framework

---

composer.lock

- Ticket: https://spryker.atlassian.net/browse/ACP-2269
- Updated `spryker/sales`.
- Updated `spryker/sales-payment`.

ACP-2269 updated dependencies

---

codeception.yml
composer.lock
config/install/docker.ci.acceptance.dynamic-store.robot.yml
config/install/docker.ci.acceptance.dynamic-store.yml
config/install/docker.ci.acceptance.robot.yml
config/install/docker.ci.acceptance.yml
config/install/docker.ci.api.dynamic-store.yml
config/install/docker.ci.api.yml
config/install/docker.yml
tests/PyzTest/Glue/PickingListsBackend/JsonApi/Fixtures/PickingListItemsBackendJsonApiFixtures.php
tests/PyzTest/Glue/PickingListsBackend/JsonApi/Fixtures/PickingListsBackendJsonApiFixtures.php
tests/PyzTest/Glue/PickingListsBackend/JsonApi/Fixtures/StartPickingBackendJsonApiFixtures.php
tests/PyzTest/Glue/PickingListsBackend/JsonApi/GetCollectionPickingListsBackendJsonApiCest.php
tests/PyzTest/Glue/PickingListsBackend/JsonApi/GetPickingListsBackendJsonApiCest.php
tests/PyzTest/Glue/PickingListsBackend/JsonApi/PickingListItemsBackendJsonApiCest.php
tests/PyzTest/Glue/PickingListsBackend/JsonApi/StartPickingBackendJsonApiCest.php
tests/PyzTest/Glue/PickingListsBackend/_support/PickingListsBackendApiTester.php
tests/PyzTest/Glue/PickingListsBackend/codeception.yml

- Ticket: https://spryker.atlassian.net/browse/CC-32771

CC-32771 Added tests for picking lists BAPI endpoints.

---

composer.lock

- Ticket: [(https://spryker.atlassian.net/browse/FRW-7609]

FRW-7609 Updated composer loc file

---

composer.lock
data/import/common/common/glossary.csv
deploy.dev.dynamic-store.yml
deploy.dynamic-store.yml

Tickets: 
- https://spryker.atlassian.net/browse/FRW-7821
- https://spryker.atlassian.net/browse/FRW-6380

FRW-7296 Integration

---

src/Pyz/Yves/ProductReviewWidget/Theme/default/components/molecules/rating-selector/rating-selector.ts

closes [CC-33525](https://spryker.atlassian.net/browse/CC-33525)

CC-33525: Fixed rating interaction inside popup

---

.github/workflows/robot-ui-e2e-tests.yml

- Ticket: https://spryker.atlassian.net/browse/CC-33768

CC-33768: Added fixes for the "Robot Regression UI E2E"

---

src/Pyz/Yves/ShopUi/Theme/default/components/molecules/quantity-counter/quantity-counter.ts
src/Pyz/Yves/ShopUi/Theme/default/components/molecules/quantity-counter/quantity-counter.twig

Fix behavior while submit quantity on async cart
https://spryker.atlassian.net/browse/CC-33794

CC-33794: Fix behavior while submit quantity on async cart

---

composer.lock
package-lock.json

Updated `composer.lock` with new cypress-tests hash.

Enabled cypress tests for epic - Async Cart reload feature.

---

.github/workflows/up-merge-latest-release-to-master-deploy.yml
.scrutinizer.yml

- Ticket: https://spryker.atlassian.net/browse/CC-33310
- Introduced the workflow to auto-merge the latest release to the "master-deploy" branch.

CC-33310: Introduced the workflow to auto-merge the latest release to the "master-deploy" branch.

---

.github/workflows/robot-ui-e2e-tests.yml

- Ticket: https://spryker.atlassian.net/browse/CC-34144

CC-34144: Adjusted GA workflow.

---

config/install/docker.yml
deploy.aop-demoshop-b2c.yml

- Ticket: https://spryker.atlassian.net/browse/ACP-3544

ACP-3544: Added MP

---

.github/workflows/ci.yml
composer.lock
package-lock.json

- Ticket: https://spryker.atlassian.net/browse/CC-34484

CC-34484: Session locking issue after recent integration on B2C and B2C Marketplace demo shops.

---

src/Pyz/Zed/Product/ProductConfig.php

- Ticket:  https://spryker.atlassian.net/browse/CC-26445

CC-26445 Integration

---

config/Shared/config_default.php

- Ticket: https://spryker.atlassian.net/browse/ACP-3930

ACP-3930: changed OMS to ForeignPaymentB2CStateMachine01

---

composer.json
composer.lock
src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.scss
src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
src/Pyz/Yves/CatalogPage/Theme/default/templates/page-layout-catalog/page-layout-catalog.twig

- Ticket: https://spryker.atlassian.net/browse/CC-34672

CC-34672 Collapsible category tree integraton

---

config/install/ci.yml
config/install/development.yml
config/install/testing.yml

- Ticket: https://spryker.atlassian.net/browse/FRW-9241

FRW-9241 Adjusted installation configs.

---

config/Shared/config_default.php
src/Pyz/Zed/KernelApp/KernelAppDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/ACP-4372

ACP-4372: Fixed ACP config

---

composer.lock
package-lock.json

- Ticket: https://spryker.atlassian.net/browse/CC-34729

CC-34729 Update Summernote dependency

---

composer.lock

- Ticket: https://spryker.atlassian.net/browse/CC-20625

Integration: CC-20625

---

.robot/Dockerfile

FRW-9423 Fix project installation.

---

composer.json
composer.lock
config/Shared/config_default.php
data/import/common/common/glossary.csv
src/Pyz/Glue/GlueApplication/GlueApplicationConfig.php
src/Pyz/Glue/GlueApplication/GlueApplicationDependencyProvider.php
src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-summary/cart-summary.twig
src/Pyz/Yves/CheckoutPage/CheckoutPageConfig.php
src/Pyz/Yves/CheckoutPage/CheckoutPageDependencyProvider.php
src/Pyz/Yves/PaymentAppWidget/PaymentAppWidgetConfig.php
src/Pyz/Yves/Router/RouterDependencyProvider.php
src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
src/Pyz/Zed/Cart/CartDependencyProvider.php
src/Pyz/Zed/Checkout/CheckoutDependencyProvider.php
src/Pyz/Zed/MessageBroker/MessageBrokerDependencyProvider.php
src/Pyz/Zed/Payment/PaymentDependencyProvider.php
src/Pyz/Zed/PaymentApp/PaymentAppDependencyProvider.php
src/Pyz/Zed/PaymentAppShipment/PaymentAppShipmentConfig.php
src/Pyz/Zed/PaymentCartConnector/PaymentCartConnectorConfig.php

- Ticket: https://spryker.atlassian.net/browse/ACP-4588
- Core PR: https://github.com/spryker-shop/suite/pull/1642

ACP-4455: Express checkout infrastructure integration.

---

composer.lock

- Ticket: https://spryker.atlassian.net/browse/ACP-4615
- Core PR: https://github.com/spryker/suite-nonsplit/pull/9231

ACP-4455: Update the modules.

---

deploy.aop-b2c-testing.yml

- Ticket: https://spryker.atlassian.net/browse/ACP-4378

ACP-4378: Changes domain for atrs scripts

---

deploy.aop-b2c-testing.yml

- Ticket: https://spryker.atlassian.net/browse/ACP-4378

ACP-4378: changed tenant

---

deploy.aop-b2c-testing.yml

- Ticket: https://spryker.atlassian.net/browse/ACP-4378

ACP-4578: fixed acp urls in build

---

composer.lock

- Ticket: https://spryker.atlassian.net/browse/ACP-4619
- Core PR: https://release.spryker.com/release-groups/view/5671

ACP-4619: Update of the modules.

---

.github/workflows/ci.yml

- Ticket: https://spryker.atlassian.net/browse/FRW-9599

FRW-9599: fix hackaton robot tests

---

composer.lock
src/Pyz/Yves/Twig/TwigDependencyProvider.php
src/Pyz/Zed/Twig/TwigDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/FRW-9287

FRW-9287 Added new twig var dumper plugin.

---

composer.lock
package-lock.json

- Ticket: https://spryker.atlassian.net/browse/CC-34954

CC-34954 Update plotly dependency

---

.github/workflows/ci.yml
.github/workflows/robot-ui-e2e-tests.yml

- Ticket: https://spryker.atlassian.net/browse/FRW-9711

FRW-9444 Trigger jobs PR on unlabeled.

---

src/Pyz/Yves/CustomerPage/Theme/default/views/profile/profile.twig

- Ticket: https://spryker.atlassian.net/browse/FRW-10067

FRW-10067 Added CustomerEmailChangeRequestWidget widget

---

composer.lock

Tickets:
- https://spryker.atlassian.net/browse/FRW-9438
- https://spryker.atlassian.net/browse/FRW-9444

Integration: FRW-9444, FRW-9438

---

config/Shared/config_default.php

- Ticket: https://spryker.atlassian.net/browse/SUPESC-887

SUPESC-887: integration

---

tests/PyzTest/Zed/CmsGui/Presentation/CmsGuiCreatePageCest.php
tests/PyzTest/Zed/CmsGui/_support/CmsGuiPresentationTester.php

- Ticket: https://spryker.atlassian.net/browse/CC-35490
Improvements
- Fixed CmsGuiCreatePageCest

CC-35490 Fixed flaky CMS page test.

---

config/install/destructive.yml

- Ticket: https://spryker.atlassian.net/browse/CC-35103
IMPORTANT: These changes should never be merged into master, only into the master-deploy branch.
- Added publish and sync into the destructive deployment to avoid flaky tests.

CC-35103 Add P&S into destructive deployment.

---

config/Shared/stores.php

- Ticket: [CC-35577](https://spryker.atlassian.net/browse/CC-35577)
- https://github.com/spryker-shop/b2b-demo-shop/pull/649
- https://github.com/spryker-shop/b2b-demo-marketplace/pull/597
- https://github.com/spryker-shop/b2c-demo-marketplace/pull/566
- https://github.com/spryker-projects/acp-e2e-testing/pull/82
- added US country to DE store

CC-35577: add US country to DE store for ACP tests

---

src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-list/navigation-list.twig

- Ticket: https://spryker.atlassian.net/browse/SUPESC-627

SUPESC-627: fixes CMS content

---

.github/actions/job-slack-notifications/action.yml

- Ticket: https://spryker.atlassian.net/browse/CC-35773

CC-35773 improved Github actions failed job notification.

---

src/Pyz/Yves/AgentPage/AgentPageConfig.php
tests/PyzTest/Zed/ProductOption/Business/ProductOptionFacadeAggregatorTest.php

CC-35509: trigger CI

---

config/install/destructive.yml

- Ticket: https://spryker.atlassian.net/browse/CC-35103
IMPORTANT: These changes should never be merged into master, only into the master-deploy branch.
- Added schedule price application and publish and sync into the destructive deployment to avoid flaky tests.

CC-35103 Added Apply Scheduled Price and P&S into destructive deployment.

---

.github/workflows/ci.yml
.github/workflows/robot-ui-e2e-tests.yml
deploy.ci.acceptance.dynamic-store-off.yml
deploy.ci.acceptance.mariadb.cypress.yml
deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml
deploy.ci.acceptance.mariadb.dynamic-store-off.robot.yml
deploy.ci.acceptance.mariadb.dynamic-store-off.yml
deploy.ci.acceptance.mariadb.prefer-lowest.yml
deploy.ci.acceptance.mariadb.robot.yml
deploy.ci.acceptance.mariadb.yml
deploy.ci.acceptance.robot.yml
deploy.ci.acceptance.yml
deploy.ci.api.dynamic-store-off.yml
deploy.ci.api.mariadb.dynamic-store-off.yml
deploy.ci.api.mariadb.robot.yml
deploy.ci.api.mariadb.yml
deploy.ci.api.yml
deploy.ci.functional.dynamic-store-off.yml
deploy.ci.functional.mariadb.dynamic-store-off.yml
deploy.ci.functional.mariadb.prefer-lowest.yml
deploy.ci.functional.mariadb.yml
deploy.ci.functional.yml
src/Pyz/Yves/Router/RouterDependencyProvider.php

- Tickets: https://spryker.atlassian.net/browse/CC-35872, https://spryker.atlassian.net/browse/CC-35922

Enabled composer cache for CI jobs.

---

composer.lock

- Ticket: https://spryker.atlassian.net/browse/FRW-10501

FRW-10501 Integration.

---

composer.lock
src/Pyz/Zed/Store/StoreDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/CC-35846

CC-35846: Added timezone to Order Table filters.

---

composer.json
composer.lock
data/import/common/common/glossary.csv
src/Pyz/Zed/Application/ApplicationDependencyProvider.php
src/Pyz/Zed/Twig/TwigDependencyProvider.php
tests/PyzTest/Yves/Checkout/Process/Steps/SummaryStepTest.php
tests/PyzTest/Zed/Console/_data/cli_sandbox/config/Shared/config_default.php
tests/PyzTest/Zed/MessageBroker/MessageHandlers/Payment/Presentation/PaymentCaptureFailedMessageCest.php
tests/PyzTest/Zed/MessageBroker/MessageHandlers/Payment/Presentation/PaymentCapturedMessageCest.php

- Ticket: https://spryker.atlassian.net/browse/FRW-10720

FRW-10720 Updated dependencies

---

composer.lock
src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/customer-navigation/customer-navigation.twig
src/Pyz/Yves/MultiFactorAuth/Theme/default/views/customer-set-up-page/set-up-page.twig

- Ticket: https://spryker.atlassian.net/browse/FRW-10754

FRW-10754 Fixes for customer account.

---

composer.json
composer.lock
src/Pyz/Yves/CheckoutPage/Theme/default/templates/page-layout-order-submitted/page-layout-order-submitted.twig

- Ticket: https://spryker.atlassian.net/browse/CC-36088

СС-36088: Fixed shipment expense calculation in case of a multi-shipment.

---

package-lock.json

- Ticket: https://spryker.atlassian.net/browse/CC-36096

CC-36096: Fixes security issue with node modules

---

composer.lock

- Ticket: https://spryker.atlassian.net/browse/FRW-10772

FRW-10776 Integration.

---

src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig

- Ticket: https://spryker.atlassian.net/browse/FRW-10760
Fixed wrongly generated URLs.

FRW 10760 Fixed 404 error on filter by category in dynamic sale category

---

composer.lock

Ticket: https://spryker.atlassian.net/browse/CC-36115

CC-36115 Integrated bugfixes.

---

composer.lock

- Ticket: https://spryker.atlassian.net/browse/FRW-10782
- Ticket: https://spryker.atlassian.net/browse/FRW-10830

FRW-10782 Upgraded MFA modules version. 

---

composer.json
composer.lock
package-lock.json

- Ticket:  https://spryker.atlassian.net/browse/CC-36099

CC-36099 tests for table filters

---

tests/PyzTest/Yves/Customer/Presentation/CustomerAddressCest.php

- Ticket: https://spryker.atlassian.net/browse/CC-35660
- Core PR: no core PR

CC-35660: Skip CustomerAddressCest.

---

composer.json
composer.lock

Ticket: https://spryker.atlassian.net/browse/CC-36139

CC-36139 Fixing flickery tests.

---

src/Pyz/Zed/DataImport/Business/Model/DiscountVoucher/DiscountVoucherWriterStep.php

- Ticket: https://spryker.atlassian.net/browse/CC-35970
- Core PR: No core PR
The purpose of this PR is to add additional logs if CI failed during the build on the data import step.

CC-35970: Flaky CI. Data Import discount voucher failed

---

deploy.aop-b2c-testing.yml
deploy.aop-consultant-b2c.yml
deploy.aop-demoshop-b2c.yml

- Ticket: https://spryker.atlassian.net/browse/SC-23578

SC-23578: Added Otel extension into ACP deploy files

---

composer.lock
config/Shared/config_default.php
config/Zed/cronjobs/jenkins.php
src/Pyz/Client/Catalog/CatalogDependencyProvider.php
src/Pyz/Client/CmsPageSearch/CmsPageSearchDependencyProvider.php
src/Pyz/Zed/MessageBroker/MessageBrokerDependencyProvider.php
src/Pyz/Zed/Publisher/PublisherDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/ACP-5354

ACP-5354: Algolia: global search to CMS and docs integration

---

composer.lock
src/Pyz/Client/Quote/QuoteDependencyProvider.php
src/Pyz/Shared/Agent/AgentConfig.php
src/Pyz/Zed/Sales/SalesDependencyProvider.php

- Ticket: https://spryker.atlassian.net/browse/CC-36205
- Core PR: https://github.com/spryker-shop/suite/pull/1872

CC-36205:  Agent Assist: Information about the agent who submitted Order (Fixathon)

---

config/install/destructive.yml

- Ticket: https://spryker.atlassian.net/browse/FRW-11070

Adjusted destructive
